### ISSUE TITLE
I need to do copy-paste operation JsTree?

### ISSUE THREAD

**Issue by mifakam** [vakata/jstree#1855]
I'm implementing a tree using jstree,i need to do copy-paste operation.But i'm not able to copy a node (parent with children) and paste it to one of its child node.I'm trying it using **jsTree-context-menu** plugin?Copy and paste are done, but its contents are not copied!? 

requirement
-----------

 - Node 1
      - Node 2
      - Node 3
 - Node 4

Assume this is my tree.I need to copy() Node 1 and need to paste under Node 2.I'm trying it using jstree-context-menu plugin and find its not working at all.
<br>So my Result Must Be With content but content is not available.
 

 - Node 1
  - Node 2
      - Node 1      <-----Pasted item 
         - Node 2
         - Node 3
  - Node 3
 - Node 4

This code for copy :

    var inst = $.jstree.reference(data.reference),
        obj = inst.get_node(data.reference);
    if (inst.is_selected(obj)) {
        inst.copy(inst.get_top_selected());
    }

This code for paste :

    var inst = $.jstree.reference(data.reference),
     obj = inst.get_node(data.reference);
     inst.paste(obj,'last');

Guide me.

Thanks in advance!

**Comment by vakata** [comment]
It is not possible to copy a node inside itself, as most of the time that will cause an endless loop.

**Comment by mifakam** [comment]
The question was corrected.

Copy is done and the paste is done, but the content is not in the pasted nodes.

**Comment by vakata** [comment]
The answer is still the same - it is not possible to copy a node inside itself

**Comment by mifakam** [comment]
Can you give me an example to work on a copy?

**Comment by shrey-code** [comment]
#I,m also implementing a tree using jstree ,i need to do copy-paste operation.But i'm not able to copy a node (parent with children) and paste it to some other node. Copy and paste operation are going smooth. but when i save the tree it doesn't updates the UI like this 

**Initial Structure**

- NFR (Parent)
   - Logging (child of NFR)
   - Tracing (child of NFR)
- Project Vision Statement 
Assume this is my tree.I need to copy() NFR along with its child nodes  and need to paste under Project Vision Statement.
After copy and paste it shows the changes like this
- NFR (Parent)
   - Logging (child of NFR)
   - Tracing (child of NFR)
- Project Vision Statement 
  - NFR
    -Logging
    - Project Vision Statement
Buyt when i save the tree and again re open it, the rendered tree body appears like this 
- NFR (Parent)
   - Logging (child of NFR)
   - Tracing (child of NFR)
- Project Vision Statement 
  - NFR 
How do i let the child nodes of NFR to be rendered alongside with NFR?
